/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.one.testTreeWindow.mainFrame;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author vtstar
 */
public class MainWindowJFrame extends JFrame {

  

    /** Creates new form MainWindowJFrame */
    public MainWindowJFrame() {
        initComponents();
        //12-27居中显示
        setLocationRelativeTo(getOwner());
        //另外设置主界面显示最大化的代码为this.setExtendedState(this.getExtendedState()|JFrame.MAXMIZED_BOTH).为了让某个控件可以随着窗体大小变化而自动调整,需要设置其水平和垂直自动调整.
        this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
        //最大化
        // 主界面在初始化时,调用LoadTree方法来填充左边的菜单树,如下所示:
        LoadTree();
    }
    
      public MainWindowJFrame(String uname){
         initComponents();
         setLocationRelativeTo(getOwner()); //居中显示
          this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH );
          LoadTree();
         // this.lblUser.setText("欢迎 "+uname+ " 登录!");
     
     }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addContainerGap(931, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //主界面初始化时，调用LoadTree 方法来填充左边的菜单树，如下所示
    private void LoadTree(){
        //自定义控件，支持关闭按钮
        //jTabbedPane1.setCloseButtonEnabled(true);
        jTabbedPane1.setCloseButtonEnabled(false);
        
        DefaultMutableTreeNode node1 = new DefaultMutableTreeNode("软件部");
        node1.add(new DefaultMutableTreeNode("产品部"));
        node1.add(new DefaultMutableTreeNode("测试部"));
        node1.add(new DefaultMutableTreeNode("设计部"));
  
        DefaultMutableTreeNode node2 = new DefaultMutableTreeNode("销售部");
        node2.add(new DefaultMutableTreeNode("jack"));
        node2.add(new DefaultMutableTreeNode("Lily"));
        node2.add(new DefaultMutableTreeNode("Smith"));
  
        DefaultMutableTreeNode top = new DefaultMutableTreeNode("职员管理");
                    
        top.add(new DefaultMutableTreeNode("总经理"));
        top.add(node1);
        top.add(node2);
        
        //JTree tree = new JTree(top);
        DefaultTreeModel model = new DefaultTreeModel(top);
        jTree1.setmodel(model);
        //jTree1.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION)
        //set jframe icon
        //注释
//     try
//        {
//        Image icon= ImageIO.read(this.getClass().getResource("/images/point.png"));
//            tabIcon = createImageIcon("/images/point.png", "tab icon");
//
//        this.setIconImage(icon);
//        }
//        catch(IOException ex)
//        {
//            System.out.println(ex);
//        }
        
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindowJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainWindowJFrame().setVisible(true);
            }
        });
    }

    //创建自定义控件
    private static class jTabbedPane1 {

        private static void setCloseButtonEnabled(boolean b) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            System.out.println("自定义控件");
        }

        public jTabbedPane1() {
            
        }

        public static void addTab(String s, ImageIcon tabIcon, JInternalFrame frm) {

        }
    }

    private static class jTree1 {

        private static void setmodel(DefaultTreeModel model) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            System.out.println("jTree1");
        }

        public jTree1() {
        }

        public static Object getLastSelectedPathComponent() {
            DefaultMutableTreeNode node2 = new DefaultMutableTreeNode("销售部");
            return node2;
        }
    }
    
 //   在Tree的值变化事件中,通过class.forName()和 cls.newInstance()反射动态实例化窗体,代码如下:
     private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {                                    
        // TODO add your handling code here:
     
       DefaultMutableTreeNode node = (DefaultMutableTreeNode) 
        jTree1.getLastSelectedPathComponent();

         if (node == null){
            //Nothing is selected.  
              return;
         }
 
         Object nodeInfo = node.getUserObject();
         String item = (String) nodeInfo;
 
         if (node.isLeaf()) {
            String item1 = (String) nodeInfo;
             // this.setTitle(item1);
             //File f = new File("client.jar");
             //URLClassLoader cl = new URLClassLoader(new URL[]{f.toURI().toURL(), null});
             //Class<?> clazz = cl.loadClass("epicurus.Client");
             //Method main = clazz.getMethod("main", String[].class);
             //main.invoke(null, new Object[]{new String[]{}});
             try {
                 Class cls = Class.forName("com.one.testTreeWindow.forms.JIFrame1");
                javax.swing.JInternalFrame frm = (javax.swing.JInternalFrame) cls.newInstance();
                  frm.setVisible(true);

                 //jTabbedPane1.addTab(" "+item1+"  ",null,frm);
                 jTabbedPane1.addTab(" "+item1+"  ",this.tabIcon,frm);

              }
             catch (Throwable e) {
                 System.err.println(e);
              }
         } else {
             System.out.println("not leaf");
         }
     }
 
 
    // 在javaswing中的路径也和net不同,下面定义了一个创建ImageIcon的方法:
      /** Returns an ImageIcon, or null if the path was invalid. */
    protected ImageIcon createImageIcon(String path,String description) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
             return new ImageIcon(imgURL, description);
         } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private  ImageIcon tabIcon;

    
     private javax.swing.JLabel lblUser;
    
}
