package com.one.javatest.transferWords.testTwo;

import org.jdesktop.beansbinding.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ItemEvent;
import java.io.IOException;

/**
 * Created by vtstar on 2018/3/6.
 */
public class TranslateJFrame extends JFrame{

 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
        /**
         * Creates new form TranslateJFrame
         */
        public TranslateJFrame() throws IOException {
            bindingGroup = new BindingGroup();
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jPanel2 = new javax.swing.JPanel();
            jPanel4 = new javax.swing.JPanel();
            jButton1 = new javax.swing.JButton();
            jButton2 = new javax.swing.JButton();
            jButton3 = new javax.swing.JButton();
            jComboBox1 = new javax.swing.JComboBox<>();
            jPanel6 = new javax.swing.JPanel();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTextArea1 = new javax.swing.JTextArea();
            jButton7 = new javax.swing.JButton();
            jPanel3 = new javax.swing.JPanel();
            jPanel5 = new javax.swing.JPanel();
            jButton4 = new javax.swing.JButton();
            jButton5 = new javax.swing.JButton();
            jButton6 = new javax.swing.JButton();
            jComboBox2 = new javax.swing.JComboBox<>();
            jPanel8 = new javax.swing.JPanel();
            jButton8 = new javax.swing.JButton();
            jScrollPane3 = new javax.swing.JScrollPane();
            jTextArea3 = new javax.swing.JTextArea();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jButton1.setText("中文");
            jButton1.setToolTipText("");
            Binding binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, jButton1, ELProperty.create("${selected}"), jButton1, BeanProperty.create("selected"), "selectFlag");
            binding.setSourceNullValue(true);
            bindingGroup.addBinding(binding);
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("英文");
            binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, jButton2, ELProperty.create("${selected}"), jButton2, BeanProperty.create("selected"), "selectFlag2");
            binding.setSourceNullValue(false);
            bindingGroup.addBinding(binding);
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jButton3.setText("韩语");
            binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, jButton3, ELProperty.create("${selected}"), jButton3, BeanProperty.create("selected"), "selectFlag3");
            binding.setSourceNullValue(false);
            bindingGroup.addBinding(binding);
            jButton3.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton3ActionPerformed(evt);
                }
            });
            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "自动检测", "英文", "韩语", "日语","中文(繁体)"}));
            jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    try {
                        jComboBox1ActionPerformed(evt);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
            jComboBox1.addItemListener(new java.awt.event.ItemListener() {
                @Override
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    TranslateJFrame.this.itemStateChanged(evt);
                }
            });

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                    jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                    jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBox1)))
            );

            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jScrollPane1.setViewportView(jTextArea1);

            jButton7.setIcon(new javax.swing.ImageIcon("D:\\SwingProjectTests\\SpringProjectsTesto\\SpringMVCDemo1\\SSH\\src\\com\\one\\javatest\\transferWords\\testTwo\\del.jpg")); // NOI18N
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
            jPanel6.setLayout(jPanel6Layout);
            jPanel6Layout.setHorizontalGroup(
                    jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
            );
            jPanel6Layout.setVerticalGroup(
                    jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                    .addComponent(jButton7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1))
            );

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                    jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addContainerGap())
            );

            jButton4.setText("简中");
            //设置默认选中
            jButton4.setSelected(true);

            binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, jButton4, ELProperty.create("${selected}"), jButton4, BeanProperty.create("selected"), "selectFlag4");
            //binding.setSourceNullValue(false);
            binding.setSourceNullValue(true);
            bindingGroup.addBinding(binding);
            jButton4.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton4ActionPerformed(evt);
                }
            });

            jButton5.setText("英语");
            jButton5.setToolTipText("");
            binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, jButton5, ELProperty.create("${selected}"), jButton5, BeanProperty.create("selected"), "selectFlag5");
            binding.setSourceNullValue(false);
            bindingGroup.addBinding(binding);
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            jButton6.setText("日语");
            jButton6.setToolTipText("");
            binding = Bindings.createAutoBinding(AutoBinding.UpdateStrategy.READ_WRITE, jButton6,ELProperty.create("${selected}"), jButton6, BeanProperty.create("selected"), "selectFlag6");
            binding.setSourceNullValue(false);
            bindingGroup.addBinding(binding);
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "中文", "英文", "韩语", "日语","中文(繁体)" }));
            jComboBox2.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    try {
                        jComboBox2ActionPerformed(evt);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
            jComboBox2.addItemListener(new java.awt.event.ItemListener() {
                @Override
                public void itemStateChanged(java.awt.event.ItemEvent evt) {
                    TranslateJFrame.this.itemStateChanged2(evt);
                }
            });
            javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
            jPanel5.setLayout(jPanel5Layout);
            jPanel5Layout.setHorizontalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel5Layout.setVerticalGroup(
                    jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jComboBox2)
                                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
            );

            jButton8.setIcon(new javax.swing.ImageIcon("D:\\SwingProjectTests\\SpringProjectsTesto\\SpringMVCDemo1\\SSH\\src\\com\\one\\javatest\\transferWords\\testTwo\\del.jpg")); // NOI18N
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                @Override
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton8ActionPerformed(evt);
                }
            });
            jTextArea3.setColumns(20);
            jTextArea3.setRows(5);
            jScrollPane3.setViewportView(jTextArea3);

            javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
            jPanel8.setLayout(jPanel8Layout);
            jPanel8Layout.setHorizontalGroup(
                    jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(60, 60, 60))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(68, 68, 68))))
            );
            jPanel8Layout.setVerticalGroup(
                    jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 29, Short.MAX_VALUE)))
                                    .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
            );

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap(30, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                    jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addContainerGap())
            );

            bindingGroup.bind();

            pack();
        }// </editor-fold>

    boolean itemChanged1Flag = false;
    /** 下拉列表1 --都走  自动检测 --> 简中 */
        private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
            // TODO add your handling code here:
            itemChanged1Flag = true;
            jComboBox1.setForeground(Color.GRAY);
            jButton6.setForeground(Color.LIGHT_GRAY);
            jButton5.setForeground(Color.LIGHT_GRAY);
            jButton4.setForeground(Color.LIGHT_GRAY);
            String result = _getjTArea3Result();
            jTextArea3.setText(result);
            System.out.println("jitem1:"+result);
            jTextArea3.setVisible(true);
            System.out.println("item1-->");
        }
        /** 简中-->*/
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
//            jButton1.setForeground(Color.cyan);
            //jButton1clicked=true;
            //jButton1.setBackground(jButton1clicked ? Color.green : Color.cyan);
            //System.out.println(bindingGroup.getBinding("selectFlag2"));
            // org.jdesktop.beansbinding.AutoBinding [name=selectFlag2,
            // sourceObject=javax.swing.JButton[,85,6,75x49,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.synth.SynthBorder@4d5c2a5f,
            // flags=288,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,
            // margin=javax.swing.plaf.InsetsUIResource[top=0,left=0,bottom=0,right=0],
            // paintBorder=true,paintFocus=true,pressedIcon=,rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,
            // selectedIcon=,text=英文,defaultCapable=true], sourceProperty=org.jdesktop.beansbinding.ELProperty[ValueExpression[${selected}]],
            // targetObject=javax.swing.JButton[,85,6,75x49,alignmentX=0.0,alignmentY=0.5,border=javax.swing.plaf.synth.SynthBorder@4d5c2a5f,flags=288,
            // maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,disabledSelectedIcon=,
            // margin=javax.swing.plaf.InsetsUIResource[top=0,left=0,bottom=0,right=0],paintBorder=true,paintFocus=true,pressedIcon=,
            // rolloverEnabled=true,rolloverIcon=,rolloverSelectedIcon=,selectedIcon=,text=英文,defaultCapable=true],
            // targetProperty=org.jdesktop.beansbinding.BeanProperty[selected], validator=null, converter=null, sourceNullValue=false,
            // targetNullValue=null, sourceUnreadableValueSet=false, sourceUnreadableValue=null, bound=true, updateStrategy=READ_WRITE]
            System.out.println(bindingGroup.getBinding("selectFlag2").getSourceNullValue());
            //bindingGroup.getBinding("selectFlag2").setSourceNullValue(false);// 不可以 Can not call this method on a bound binding
            itemChanged1Flag = false;
            jButton1.setForeground(Color.GRAY);
            jButton2.setForeground(Color.LIGHT_GRAY);
            jButton3.setForeground(Color.LIGHT_GRAY);
            jComboBox1.setForeground(Color.LIGHT_GRAY);
            String result = _getjTArea3Result();
            jTextArea3.setText(result);
            System.out.println("简中-->");
        }
    /** 英文-->*/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        itemChanged1Flag = false;
        jButton2.setForeground(Color.GRAY);
        jButton1.setForeground(Color.LIGHT_GRAY);
        jButton3.setForeground(Color.LIGHT_GRAY);
        jComboBox1.setForeground(Color.LIGHT_GRAY);
        String result = _getjTArea3Result();
        jTextArea3.setText(result);
        System.out.println("英文-->");
    }
    /** 韩语-->*/
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        itemChanged1Flag = false;
        jButton3.setForeground(Color.GRAY);
        jButton1.setForeground(Color.LIGHT_GRAY);
        jButton2.setForeground(Color.LIGHT_GRAY);
        jComboBox1.setForeground(Color.LIGHT_GRAY);
        String result = _getjTArea3Result();
        jTextArea3.setText(result);
        System.out.println("韩语-->");
    }
    /** 删除*/
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTextArea1.setText("");
        String result = _getjTArea3Result();
        jTextArea3.setText(result);
        System.out.println("删除7-->");
    }
    /** 删除*/
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTextArea3.setText("");
        System.out.println("-->删除");
    }
    /** -->简中*/
     boolean itemChanged2Flag = false;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        itemChanged2Flag = false;
        jButton4.setForeground(Color.GRAY);
        jButton5.setForeground(Color.LIGHT_GRAY);
        jButton6.setForeground(Color.LIGHT_GRAY);
        jComboBox2.setForeground(Color.LIGHT_GRAY);
        String result = _getjTArea3Result();
        jTextArea3.setText(result);
        System.out.println("jButton4:"+result);
        jTextArea3.setVisible(true);
        System.out.println("-->简中");

    }
    /** 英语-->*/
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        itemChanged2Flag = false;
        jButton5.setForeground(Color.GRAY);
        jButton4.setForeground(Color.LIGHT_GRAY);
        jButton6.setForeground(Color.LIGHT_GRAY);
        jComboBox2.setForeground(Color.LIGHT_GRAY);
        String result = _getjTArea3Result();
        jTextArea3.setText(result);
        System.out.println("jButton5:"+result);
        jTextArea3.setVisible(true);
        System.out.println("-->英语");
    }
    /** 日语-->*/
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        itemChanged2Flag = false;
        jButton6.setForeground(Color.GRAY);
        jButton5.setForeground(Color.LIGHT_GRAY);
        jButton4.setForeground(Color.LIGHT_GRAY);
        jComboBox2.setForeground(Color.LIGHT_GRAY);
        String result = _getjTArea3Result();
        jTextArea3.setText(result);
        System.out.println("jButton6:"+result);
        jTextArea3.setVisible(true);
        System.out.println("-->日语");
    }
    private void itemStateChanged(java.awt.event.ItemEvent evt) {
        // TODO add your handling code here:
        int state = evt.getStateChange();
        System.out.println((state == ItemEvent.SELECTED)?"Selected":"Deselected");//Deselected
        System.out.println("Item:"+evt.getItem());//中文
        ItemSelectable itemSelectable = evt.getItemSelectable();
        System.out.println(", Selected: " + selectedString(itemSelectable));//英文
    }

    private void itemStateChanged2(java.awt.event.ItemEvent evt) {
        // TODO add your handling code here:
        int state = evt.getStateChange();
        System.out.println((state == ItemEvent.SELECTED)?"Selected":"Deselected");//Deselected
        System.out.println("Item:"+evt.getItem());//中文
        ItemSelectable itemSelectable = evt.getItemSelectable();
        System.out.println(", Selected: " + selectedString(itemSelectable));//英文
        /***/
        System.out.println("jComboBox2.getSelectedItem():"+jComboBox2.getSelectedItem());// 英文
        itemChanged2Flag = true;
        jComboBox2.setForeground(Color.GRAY);
        jButton6.setForeground(Color.LIGHT_GRAY);
        jButton5.setForeground(Color.LIGHT_GRAY);
        jButton4.setForeground(Color.LIGHT_GRAY);
        String result = _getjTArea3Result();
        jTextArea3.setText(result);
        System.out.println("jitem2:"+result);
        jTextArea3.setVisible(true);
        System.out.println("-->item2");
    }
    private String selectedString(ItemSelectable is) {
        Object selected[] = is.getSelectedObjects();
        return ((selected.length == 0) ? "null" : (String) selected[0]);
    }

    /** 下拉列表2 --都走   --> 列表 */
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
        // TODO add your handling code here:
        System.out.println("Selected index=" + ((JComboBox)evt.getSource()).getItemCount());//5
        System.out.println("jComboBox2.getSelectedItem():"+jComboBox2.getSelectedItem());// 英文
        if(itemChanged2Flag==true){
            String result = _getjTArea3Result();
            jTextArea3.setText(result);
            System.out.println("jitem2:"+result);
            jTextArea3.setVisible(true);
            System.out.println("-->item2");
     }

    }


    /**获取 翻译 后 的 值*/
    public String _getjTArea3Result(){
        String jTAreainput = jTextArea1.getText();
        String jCBox2value = (String) jComboBox2.getSelectedItem();
        System.out.println("jTAreainput:"+jTAreainput);
//        boolean selectFlag4 = (boolean) bindingGroup.getBinding("seletFalg4").getSourceNullValue();// 简中
//        boolean selectFlag5 = (boolean) bindingGroup.getBinding("seletFalg5").getSourceNullValue();// 英语
//        boolean selectFlag6 = (boolean) bindingGroup.getBinding("seletFalg6").getSourceNullValue();// 日语
        Color color4 = jButton4.getForeground(); // Color.LIGHT_GRAY      Color.GRAY
        Color color5 = jButton5.getForeground(); //英
        Color color6 = jButton6.getForeground();// 日语
        Color colorbox = jComboBox2.getForeground();//item
        System.out.println(jComboBox2.getSelectedObjects());
        //System.out.println("color5:"+jButton5.getForeground().toString()); // DerivedColor(color=0,0,0 parent=text offsets=0.0,0.0,0.0,0 pColor=0,0,0
                                               //  java.awt.Color[r=128,g=128,b=128]

        String result = "";
        try {
            if(color4==Color.GRAY){
                result = TranslateUtil.auto(jTAreainput);;
            }else if(color5==Color.GRAY){
                result = TranslateUtil.cn2en(jTAreainput);
            }else if(color6==Color.GRAY){
                result = TranslateUtil.cn2ja(jTAreainput);
            }else if(colorbox==Color.GRAY){
                //  "中文", "英文", "韩语", "日语","中文(繁体)"
                if(jCBox2value.equals("中文")){
                    result = TranslateUtil.auto(jTAreainput);
                }if(jCBox2value.equals("英文")){
                    result = TranslateUtil.auto2cn(jTAreainput);
                }if(jCBox2value.equals("韩语")){
                    result = TranslateUtil.auto2ko(jTAreainput);
                }if(jCBox2value.equals("日语")){
                    result = TranslateUtil.auto2jp(jTAreainput);
                }if(jCBox2value.equals("中文(繁体)")){
                    result = TranslateUtil.auto2tw(jTAreainput);
                }
            }
            //result = TranslateUtil.auto(jTAreainput);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return result;
    }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(TranslateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(TranslateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(TranslateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(TranslateJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

        /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    try {
                        new TranslateJFrame().setVisible(true);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            });
        }

        // Variables declaration - do not modify
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JButton jButton6;
        private javax.swing.JButton jButton7;
        private javax.swing.JButton jButton8;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JComboBox<String> jComboBox2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel8;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JTextArea jTextArea1;
        private javax.swing.JTextArea jTextArea3;
        private BindingGroup bindingGroup;
    //
        // End of variables declaration


}
